### ISSUE TITLE
Included Data::Verifier incomplete?

### ISSUE THREAD

**Issue by eserte** [eokoe/CatalystX-Eta#1]
See http://www.cpantesters.org/cpan/report/68bac66c-ca1c-11e4-9ada-7b7be0bfc7aa for a sample fail report -> Data::Verifier::Field is missing here. And looking at other fail reports (see http://matrix.cpantesters.org/?dist=CatalystX-Eta%200.0362 for the complete list) it seems that other test prereqs are missing.

**Comment by renatocron** [comment]
I will see that, thanks for reporting

**Comment by renatocron** [comment]
https://github.com/eokoe/CatalystX-Eta/commit/3d3803232aac1635eac3e9e6efb94ea8e3a7b15e

A lot of things was missing on tests!

**Comment by eserte** [comment]
Yes, but http://matrix.cpantesters.org/?dist=CatalystX-Eta%200.043 looks fine now.
